import AA from "../../Component/photos/AA.jpg"
const LeftEditordata=[

    {
        image:AA,
        title:"Lorem Ipsum” generator",
        description:"64Mcrbn dpsun kcmcr sdt gnbt, fcesbftbtubr gkdpdsfde` bmdt. Ngbfbegs pcrttdtcrfce`ub ngssg. Jusfb pcsubrb, ng`eg sbk pumvdegr umtrdfdbs, purus mbftus ngmbsugkgmdibrc, sdt gnbt fcnnckc ng`eg brcs quds ureg. Euef vdvbrrg dnpbrkdbt bedn. Jusfbbst. Zdvgnus g tbmmus. \bmmbetbsqub agidtget ncrid trdstdqub sbebftus bt ebtus btngmbsugkg jgnbs gf turpds b`bstgs. \rcde pagrbtrg eceunny pbkb. Ngurds bt crfd.Gbebge ebf mcrbn. De pcrttdtcr. Kcebf mgcrbbt eceunny gu`ub. Vuspbekdssb kud purus,sfbmbrdsqub gt, vumputgtb vdtgb, prbtdun ngttds, euef. Ngurds b`bt ebqub gt sbnvbebegtds bmbdjbek. Rt eceunny. Jusfb gmdqubt pbkb ece pbkb. Vuspbekdssb kgpdiusmcrbn pbmmbetbsqub ng`eg. Detb`br eummg. Kcebf imgekdt jbu`dgt md`umg. Kcebfabekrbrdt, jbmds bt dnpbrkdbt budsnck, purus dpsun prbtdun nbtus, de mgfdedg eummgedsm b`bt sgpdbe. Kcebf ut bst de mbftus fcesbqugt fcesbqugt. Btdgn b`bt kud.Gmdqugn brgt vcmutpgt. Vbk gt mcrbn de euef pcrtg trdstdqub. \rcde ebf gu`ub.Wudsqub gmdqugn tbnpcr ng`eg. \bmmbetbsqub agidtget ncrid trdstdqub sbebftus btebtus bt ngmbsugkg jgnbs gf turpds b`bstgs. Euef gf ng`eg. Ngbfbegs ckdc kcmcr,vumputgtb vbm, guftcr gf, gffunsge dk, jbmds. \bmmbetbsqub fursus sg`dttds jbmds.\bmmbetbsqub pcrttdtcr, vbmdt mgfdedg b`bstgs guftcr, kdgn brcs tbnpus grfu, ebfvumputgtb gu`ub ng`eg vbm rdsus. Frgs ece ng`eg vbm getb gkdpdsfde` racefus.Zdvgnus g nd. Ncrid ebqub. Gmdqugn brgt vcmutpgt. Detb`br umtrdfbs mcicrtds brcs.\bmmbetbsqub agidtget ncrid trdstdqub sbebftus bt ebtus bt ngmbsugkg jgnbs gfturpds b`bstgs. \rcde sbnpbr, getb vdtgb scmmdfdtukde pcsubrb, nbtus qugn dgfumdsedia, vdtgb sfbmbrdsqub euef ngssg b`bt pbkb. Vbk vbmdt ureg, detbrkun vbm,umtrdfdbs vbm, jgufdius gt, qugn. Kcebf bmdt bst, fcesbftbtubr b`bt, fcesbqugtquds, tbnpus quds, wdsd. De de euef. Fmgss gptbet tgfdtd scfdcsqu gk mdtcrgtcrqubet pbr fceuidg ecstrg, pbr defbptcs aynbegbcs. Kcebf ummgnfcrpbr jrde`dmmgbrcs. Jusfb de sgpdbe bu purus kgpdius fcnnckc. Fun scfdds egtcqub pbegtdius btng`eds kds pgrturdbet ncetbs, egsfbtur rdkdfumus nus. Frgs jgufdius fcekdnbetunckdc. Vbk gf md`umg. Gmdqugn gt brcs. Btdgn gt md`umg bt tbmmus ummgnfcrpbrumtrdfbs. De jbrnbetun, mcrbn ece fursus pcrttdtcr, kdgn ureg gffunsge mgfus, sbkdetbrkun wdsd edia ebf edsmlorem is not just a normal snippet—it’s actually a generator. Every time you expand it, it will generate a 30-words dummy text, splitted into a few sentences.",
    },
];
export {LeftEditordata};